import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/src/Components/Navbar/Navbar';
import Footer from '@/src/Components/Footer/Footer';
import { LanguageProvider } from '@/src/Context/LanguageContext';
import { CartProvider } from '@/src/Context/CartContext';
import DirectionProvider from '@/src/Components/DirectionProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          <CartProvider>
            <DirectionProvider>
              <Navbar />
              {children}
              <Footer />
            </DirectionProvider>
          </CartProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
